version: "3.11"
services:
  fastapi:
    build: ./backend  # Fast api project directory
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - APP_NAME=FastAPI App

  streamlit:
    build: ./frontend  # Streamlit project directory
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - fastapi
    environment:
      - APP_NAME=Streamlit App